.TH "src/ Directory Reference" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBheader\fP"
.br
.ti -1c
.RI "directory \fBtest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchromosome\&.cpp\fP"
.br
.RI "\fIEncapsulates the data of a chromosome in the genetic algorithm\&. \fP"
.ti -1c
.RI "file \fBfitness\&.cpp\fP"
.br
.RI "\fIEvaluate the fitness of a given chromosome\&. \fP"
.ti -1c
.RI "file \fBgenetic\&.cpp\fP"
.br
.RI "\fIGenetic Algorithm to create 12 bar blues\&. \fP"
.ti -1c
.RI "file \fBMIDI-output\&.cpp\fP"
.br
.RI "\fICreate MIDI files out of chromosomes\&. \fP"
.in -1c
