.TH "src/test/ Directory Reference" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtestchrom\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtestfit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtestmidi\&.cpp\fP"
.br
.in -1c
