.TH "src/chromosome.cpp" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/chromosome.cpp \- 
.PP
Encapsulates the data of a chromosome in the genetic algorithm\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'header/chromosome\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Encapsulates the data of a chromosome in the genetic algorithm\&. 

\fBAuthor:\fP
.RS 4
Taylor Ritenour 
.RE
.PP
\fBDate:\fP
.RS 4
July 31, 2012 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI-Generator from the source code\&.
