.TH "event" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtime\fP"
.br
.ti -1c
.RI "int \fBnote\fP"
.br
.ti -1c
.RI "char \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI-Generator from the source code\&.
