.TH "src/fitness.cpp" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fitness.cpp \- 
.PP
Evaluate the fitness of a given chromosome\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'header/chromosome\&.h'\fP
.br
\fC#include 'header/fitness\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinChord\fP (int \fBnote\fP, int key, int chord)"
.br
.ti -1c
.RI "int \fBnote_score\fP (int \fBnote\fP, int key, int articulation, int timing, int chord)"
.br
.ti -1c
.RI "int \fBrhythm_score\fP (int articulation, int timing)"
.br
.ti -1c
.RI "void \fBcreateAccompaniment\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Evaluate the fitness of a given chromosome\&. 

\fBAuthor:\fP
.RS 4
Aaron Huffman 
.RE
.PP
\fBDate:\fP
.RS 4
July 31, 2012 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI-Generator from the source code\&.
