.TH "src/header/genetic.h" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/genetic.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHROMO_LENGTH\fP   385"
.br
.ti -1c
.RI "#define \fBCROSSOVER_RATE\fP   0\&.9"
.br
.ti -1c
.RI "#define \fBWINNER_RATE\fP   0\&.95"
.br
.ti -1c
.RI "#define \fBMUTATION_RATE\fP   0\&.9"
.br
.ti -1c
.RI "#define \fBPOP_SIZE\fP   50"
.br
.ti -1c
.RI "#define \fBPOP_REMAIN_LOWBOUND\fP   45"
.br
.ti -1c
.RI "#define \fBMAX_ITERATIONS\fP   1000000"
.br
.ti -1c
.RI "#define \fBFITNESS_THRESHOLD\fP   950\&.0f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHROMO_LENGTH   385"

.SS "#define CROSSOVER_RATE   0\&.9"

.SS "#define FITNESS_THRESHOLD   950\&.0f"

.SS "#define MAX_ITERATIONS   1000000"

.SS "#define MUTATION_RATE   0\&.9"

.SS "#define POP_REMAIN_LOWBOUND   45"

.SS "#define POP_SIZE   50"

.SS "#define WINNER_RATE   0\&.95"

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI-Generator from the source code\&.
