.TH "note" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
note \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.ti -1c
.RI "char \fBpitch\fP"
.br
.ti -1c
.RI "char \fBvelocity\fP"
.br
.ti -1c
.RI "bool \fBmelody\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI-Generator from the source code\&.
