.TH "src/test/testfit.cpp" 3 "Tue Jul 31 2012" "Version 1.0" "MIDI-Generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/testfit.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include '\&.\&./header/chromosome\&.h'\fP
.br
\fC#include '\&.\&./header/fitness\&.h'\fP
.br
\fC#include '\&.\&./header/MIDI-output\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for MIDI-Generator from the source code\&.
